# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1195, 900)
        Form.setStyleSheet("QWidget{\n"
"background-color:rgb(22, 0, 34);\n"
"\n"
"}")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 1200, 900))
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.splitter.setLineWidth(1)
        self.splitter.setMidLineWidth(0)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(5)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.tabConf = QtWidgets.QTabWidget(self.splitter)
        self.tabConf.setMaximumSize(QtCore.QSize(400, 16777215))
        self.tabConf.setStyleSheet("QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 8px solid #C2C7CB;\n"
"    \n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 0px; /* move to the right by 5px */\n"
"}\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    \n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    border: 4px solid #C4C4C3;\n"
"    border-bottom-color: black; /* same as the pane color */\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"    color:white;\n"
"    background-color:rgb(5, 1, 15);\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"    color:white;\n"
"    background-color:rgb(5, 1, 15);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: #9B9B9B;\n"
"    border-bottom-color: black; /* same as pane color */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"}\n"
"")
        self.tabConf.setObjectName("tabConf")
        self.tab_Configure = QtWidgets.QWidget()
        self.tab_Configure.setStyleSheet("QWidget{\n"
"\n"
"background-color:rgb(140, 140, 105)\n"
"\n"
"}")
        self.tab_Configure.setObjectName("tab_Configure")
        self.frame = QtWidgets.QFrame(self.tab_Configure)
        self.frame.setGeometry(QtCore.QRect(20, 12, 361, 431))
        self.frame.setStyleSheet("background-color: rgb(91, 91, 91);")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(11, 21, 61, 16))
        self.label.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(11, 47, 61, 16))
        self.label_3.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(11, 73, 73, 16))
        self.label_5.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(11, 99, 61, 16))
        self.label_4.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(11, 125, 67, 16))
        self.label_7.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(11, 151, 71, 16))
        self.label_6.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_6.setObjectName("label_6")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(11, 177, 86, 16))
        self.label_9.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_9.setObjectName("label_9")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(11, 203, 61, 16))
        self.label_8.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_8.setObjectName("label_8")
        self.Line_ExhaustTemp = QtWidgets.QLineEdit(self.frame)
        self.Line_ExhaustTemp.setGeometry(QtCore.QRect(103, 177, 151, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Line_ExhaustTemp.setPalette(palette)
        self.Line_ExhaustTemp.setAutoFillBackground(False)
        self.Line_ExhaustTemp.setStyleSheet("background-color:white;\n"
"border-radius:4px;")
        self.Line_ExhaustTemp.setObjectName("Line_ExhaustTemp")
        self.Line_SeaTemp = QtWidgets.QLineEdit(self.frame)
        self.Line_SeaTemp.setGeometry(QtCore.QRect(103, 151, 151, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Line_SeaTemp.setPalette(palette)
        self.Line_SeaTemp.setAutoFillBackground(False)
        self.Line_SeaTemp.setStyleSheet("background-color:white;\n"
"border-radius:4px;")
        self.Line_SeaTemp.setObjectName("Line_SeaTemp")
        self.Line_ChargeairTemp = QtWidgets.QLineEdit(self.frame)
        self.Line_ChargeairTemp.setGeometry(QtCore.QRect(103, 99, 151, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Line_ChargeairTemp.setPalette(palette)
        self.Line_ChargeairTemp.setAutoFillBackground(False)
        self.Line_ChargeairTemp.setStyleSheet("background-color:white;\n"
"border-radius:4px;")
        self.Line_ChargeairTemp.setObjectName("Line_ChargeairTemp")
        self.Line_LubeTemp = QtWidgets.QLineEdit(self.frame)
        self.Line_LubeTemp.setGeometry(QtCore.QRect(103, 125, 151, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Line_LubeTemp.setPalette(palette)
        self.Line_LubeTemp.setAutoFillBackground(False)
        self.Line_LubeTemp.setStyleSheet("background-color:white;\n"
"border-radius:4px;")
        self.Line_LubeTemp.setObjectName("Line_LubeTemp")
        self.Line_HtWaterTemp = QtWidgets.QLineEdit(self.frame)
        self.Line_HtWaterTemp.setGeometry(QtCore.QRect(103, 47, 151, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Line_HtWaterTemp.setPalette(palette)
        self.Line_HtWaterTemp.setAutoFillBackground(False)
        self.Line_HtWaterTemp.setStyleSheet("background-color:white;\n"
"border-radius:4px;")
        self.Line_HtWaterTemp.setObjectName("Line_HtWaterTemp")
        self.Line_LtWaterTemp = QtWidgets.QLineEdit(self.frame)
        self.Line_LtWaterTemp.setGeometry(QtCore.QRect(103, 21, 151, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Line_LtWaterTemp.setPalette(palette)
        self.Line_LtWaterTemp.setAutoFillBackground(False)
        self.Line_LtWaterTemp.setStyleSheet("background-color:white;\n"
"border-radius:4px;")
        self.Line_LtWaterTemp.setObjectName("Line_LtWaterTemp")
        self.Line_RPM = QtWidgets.QLineEdit(self.frame)
        self.Line_RPM.setGeometry(QtCore.QRect(103, 203, 151, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Line_RPM.setPalette(palette)
        self.Line_RPM.setAutoFillBackground(False)
        self.Line_RPM.setStyleSheet("background-color:white;\n"
"border-radius:4px;")
        self.Line_RPM.setObjectName("Line_RPM")
        self.Line_ThrustTemp = QtWidgets.QLineEdit(self.frame)
        self.Line_ThrustTemp.setGeometry(QtCore.QRect(103, 73, 151, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Line_ThrustTemp.setPalette(palette)
        self.Line_ThrustTemp.setAutoFillBackground(False)
        self.Line_ThrustTemp.setStyleSheet("background-color:white;\n"
"border-radius:4px;")
        self.Line_ThrustTemp.setObjectName("Line_ThrustTemp")
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setGeometry(QtCore.QRect(120, 0, 191, 16))
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: BOLD;")
        self.label_10.setObjectName("label_10")
        self.label_29 = QtWidgets.QLabel(self.frame)
        self.label_29.setGeometry(QtCore.QRect(11, 379, 61, 16))
        self.label_29.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_29.setObjectName("label_29")
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(11, 327, 67, 16))
        self.label_27.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame)
        self.label_28.setGeometry(QtCore.QRect(11, 353, 61, 16))
        self.label_28.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_28.setObjectName("label_28")
        self.Line_HtWaterPress = QtWidgets.QLineEdit(self.frame)
        self.Line_HtWaterPress.setGeometry(QtCore.QRect(103, 379, 151, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Line_HtWaterPress.setPalette(palette)
        self.Line_HtWaterPress.setAutoFillBackground(False)
        self.Line_HtWaterPress.setStyleSheet("background-color:white;\n"
"border-radius:4px;")
        self.Line_HtWaterPress.setObjectName("Line_HtWaterPress")
        self.label_26 = QtWidgets.QLabel(self.frame)
        self.label_26.setGeometry(QtCore.QRect(11, 301, 61, 16))
        self.label_26.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_26.setObjectName("label_26")
        self.Line_LtWaterPress = QtWidgets.QLineEdit(self.frame)
        self.Line_LtWaterPress.setGeometry(QtCore.QRect(103, 353, 151, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Line_LtWaterPress.setPalette(palette)
        self.Line_LtWaterPress.setAutoFillBackground(False)
        self.Line_LtWaterPress.setStyleSheet("background-color:white;\n"
"border-radius:4px;")
        self.Line_LtWaterPress.setObjectName("Line_LtWaterPress")
        self.Line_FuelPress = QtWidgets.QLineEdit(self.frame)
        self.Line_FuelPress.setGeometry(QtCore.QRect(103, 301, 151, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Line_FuelPress.setPalette(palette)
        self.Line_FuelPress.setAutoFillBackground(False)
        self.Line_FuelPress.setStyleSheet("background-color:white;\n"
"border-radius:4px;")
        self.Line_FuelPress.setObjectName("Line_FuelPress")
        self.Line_ScavengePress = QtWidgets.QLineEdit(self.frame)
        self.Line_ScavengePress.setGeometry(QtCore.QRect(103, 405, 151, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Line_ScavengePress.setPalette(palette)
        self.Line_ScavengePress.setAutoFillBackground(False)
        self.Line_ScavengePress.setStyleSheet("background-color:white;\n"
"border-radius:4px;")
        self.Line_ScavengePress.setObjectName("Line_ScavengePress")
        self.label_30 = QtWidgets.QLabel(self.frame)
        self.label_30.setGeometry(QtCore.QRect(11, 405, 61, 16))
        self.label_30.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_30.setObjectName("label_30")
        self.Line_SeaPress = QtWidgets.QLineEdit(self.frame)
        self.Line_SeaPress.setGeometry(QtCore.QRect(103, 275, 151, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Line_SeaPress.setPalette(palette)
        self.Line_SeaPress.setAutoFillBackground(False)
        self.Line_SeaPress.setStyleSheet("background-color:white;\n"
"border-radius:4px;")
        self.Line_SeaPress.setObjectName("Line_SeaPress")
        self.label_25 = QtWidgets.QLabel(self.frame)
        self.label_25.setGeometry(QtCore.QRect(11, 275, 61, 16))
        self.label_25.setStyleSheet("background-color: rgb(189, 189, 189);\n"
"color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";")
        self.label_25.setObjectName("label_25")
        self.Line_LubePress = QtWidgets.QLineEdit(self.frame)
        self.Line_LubePress.setGeometry(QtCore.QRect(103, 327, 151, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.Line_LubePress.setPalette(palette)
        self.Line_LubePress.setAutoFillBackground(False)
        self.Line_LubePress.setStyleSheet("background-color:white;\n"
"border-radius:4px;")
        self.Line_LubePress.setObjectName("Line_LubePress")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(10, 250, 329, 16))
        self.line.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line.setLineWidth(3)
        self.line.setMidLineWidth(0)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.label_31 = QtWidgets.QLabel(self.frame)
        self.label_31.setGeometry(QtCore.QRect(140, 230, 101, 20))
        self.label_31.setStyleSheet("color: rgb(255, 255, 255);\n"
"FONT:BOLD;")
        self.label_31.setObjectName("label_31")
        self.pb_inputsetting = QtWidgets.QPushButton(self.tab_Configure)
        self.pb_inputsetting.setGeometry(QtCore.QRect(30, 480, 91, 51))
        self.pb_inputsetting.setObjectName("pb_inputsetting")
        self.frame_2 = QtWidgets.QFrame(self.tab_Configure)
        self.frame_2.setGeometry(QtCore.QRect(210, 460, 171, 91))
        self.frame_2.setStyleSheet("background-color:red;\n"
"border-radius:15px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(50, 20, 81, 51))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.tabConf.addTab(self.tab_Configure, "")
        self.tab_SerialSettings = QtWidgets.QWidget()
        self.tab_SerialSettings.setStyleSheet("QWidget{\n"
"\n"
"background-color:rgb(140, 140, 105)\n"
"\n"
"}")
        self.tab_SerialSettings.setObjectName("tab_SerialSettings")
        self.tabConf.addTab(self.tab_SerialSettings, "")
        self.tabDesign = QtWidgets.QTabWidget(self.splitter)
        self.tabDesign.setEnabled(True)
        self.tabDesign.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabDesign.setStyleSheet("\n"
"QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 8px solid #C2C7CB;\n"
"    \n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 0px; /* move to the right by 5px */\n"
"    right:0px;\n"
"}\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    \n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"    border: 4px solid #C4C4C3;\n"
"    border-bottom-color: black; /* same as the pane color */\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"    color:white;\n"
"    background-color:rgb(5, 1, 15);\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #fafafa, stop: 0.4 #f4f4f4,\n"
"                                stop: 0.5 #e7e7e7, stop: 1.0 #fafafa);\n"
"    color:white;\n"
"    background-color:rgb(5, 1, 15);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: #9B9B9B;\n"
"    border-bottom-color: black; /* same as pane color */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"}")
        self.tabDesign.setMovable(True)
        self.tabDesign.setTabBarAutoHide(False)
        self.tabDesign.setObjectName("tabDesign")
        self.Tab_Conf = QtWidgets.QWidget()
        self.Tab_Conf.setStyleSheet("QWidget{\n"
"background-color:rgb(255, 170, 0);\n"
"\n"
"}")
        self.Tab_Conf.setObjectName("Tab_Conf")
        self.tabDesign.addTab(self.Tab_Conf, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setStyleSheet("QWidget{\n"
"background-color:rgb(255, 170, 0);\n"
"\n"
"}")
        self.tab_2.setObjectName("tab_2")
        self.frame_SeaWaterPump = QtWidgets.QFrame(self.tab_2)
        self.frame_SeaWaterPump.setGeometry(QtCore.QRect(40, 40, 211, 161))
        self.frame_SeaWaterPump.setStyleSheet("QFrame{\n"
"    background-color:rgb(193, 193, 145) ;\n"
"}")
        self.frame_SeaWaterPump.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_SeaWaterPump.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_SeaWaterPump.setObjectName("frame_SeaWaterPump")
        self.label_11 = QtWidgets.QLabel(self.frame_SeaWaterPump)
        self.label_11.setGeometry(QtCore.QRect(130, 50, 47, 13))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_SeaWaterPump)
        self.label_12.setGeometry(QtCore.QRect(130, 90, 47, 13))
        self.label_12.setObjectName("label_12")
        self.pushButton = QtWidgets.QPushButton(self.frame_SeaWaterPump)
        self.pushButton.setGeometry(QtCore.QRect(120, 120, 61, 31))
        self.pushButton.setStyleSheet("background-color: rgb(17, 255, 92);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_SeaWaterPump)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 120, 61, 31))
        self.pushButton_2.setStyleSheet("background-color: rgb(17, 255, 92);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_32 = QtWidgets.QLabel(self.frame_SeaWaterPump)
        self.label_32.setGeometry(QtCore.QRect(20, 50, 81, 21))
        self.label_32.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_32.setText("")
        self.label_32.setObjectName("label_32")
        self.label_34 = QtWidgets.QLabel(self.frame_SeaWaterPump)
        self.label_34.setGeometry(QtCore.QRect(40, 10, 141, 20))
        self.label_34.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_34.setObjectName("label_34")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_SeaWaterPump)
        self.lineEdit.setGeometry(QtCore.QRect(20, 89, 81, 21))
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setGeometry(QtCore.QRect(50, 230, 211, 161))
        self.frame_4.setStyleSheet("QFrame{\n"
"    background-color:rgb(193, 193, 145) ;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_38 = QtWidgets.QLabel(self.frame_4)
        self.label_38.setGeometry(QtCore.QRect(130, 50, 47, 13))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.frame_4)
        self.label_39.setGeometry(QtCore.QRect(130, 90, 47, 13))
        self.label_39.setObjectName("label_39")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_9.setGeometry(QtCore.QRect(120, 120, 61, 31))
        self.pushButton_9.setStyleSheet("background-color: rgb(17, 255, 92);")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 120, 61, 31))
        self.pushButton_10.setStyleSheet("background-color: rgb(17, 255, 92);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_40 = QtWidgets.QLabel(self.frame_4)
        self.label_40.setGeometry(QtCore.QRect(20, 50, 81, 21))
        self.label_40.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.frame_4)
        self.label_41.setGeometry(QtCore.QRect(40, 10, 141, 20))
        self.label_41.setStyleSheet("font: 75 12pt \"Times New Roman\";")
        self.label_41.setObjectName("label_41")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 89, 81, 21))
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.tabDesign.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("QWidget{\n"
"background-color:rgb(255, 170, 0);\n"
"\n"
"}")
        self.tab.setObjectName("tab")
        self.tabDesign.addTab(self.tab, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setStyleSheet("QWidget{\n"
"background-color:rgb(255, 170, 0);\n"
"\n"
"}")
        self.tab_5.setObjectName("tab_5")
        self.tabDesign.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setStyleSheet("QWidget{\n"
"background-color:rgb(255, 170, 0);\n"
"\n"
"}")
        self.tab_6.setObjectName("tab_6")
        self.tabDesign.addTab(self.tab_6, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setStyleSheet("")
        self.tab_3.setObjectName("tab_3")
        self.listWidget = QtWidgets.QListWidget(self.tab_3)
        self.listWidget.setGeometry(QtCore.QRect(0, 1, 791, 861))
        self.listWidget.setStyleSheet("QListWidget {\n"
"    background-color: white;\n"
"    color:green;\n"
"    font:bold;\n"
"    border:5px;\n"
"    border-color: rgb(0, 0, 0);\n"
"    alternate-background-color: rgb(45, 255, 127);\n"
"}\n"
"\n"
"QListWidget::item:selected:active {\n"
"    \n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #6a6ea9, stop: 1 #888dd9);\n"
"}")
        self.listWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.listWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.listWidget.setAutoScroll(False)
        self.listWidget.setProperty("showDropIndicator", True)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.listWidget.setDefaultDropAction(QtCore.Qt.TargetMoveAction)
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setSelectionRectVisible(True)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.tabDesign.addTab(self.tab_3, "")

        self.retranslateUi(Form)
        self.tabConf.setCurrentIndex(0)
        self.tabDesign.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "LT Water"))
        self.label_3.setText(_translate("Form", "HT Water"))
        self.label_5.setText(_translate("Form", "Thrust Bearing "))
        self.label_4.setText(_translate("Form", "Charge Air"))
        self.label_7.setText(_translate("Form", "Lubricating Oil"))
        self.label_6.setText(_translate("Form", "Sea Water"))
        self.label_9.setText(_translate("Form", "Cylinders Exhaust"))
        self.label_8.setText(_translate("Form", "RPM"))
        self.label_10.setText(_translate("Form", "TEMPERATURES"))
        self.label_29.setText(_translate("Form", "HT Water"))
        self.label_27.setText(_translate("Form", "Lubricating Oil"))
        self.label_28.setText(_translate("Form", "LT Water"))
        self.label_26.setText(_translate("Form", "Fuel Oil"))
        self.label_30.setText(_translate("Form", "Scavenge "))
        self.label_25.setText(_translate("Form", "sea water"))
        self.label_31.setText(_translate("Form", "PRESSURES"))
        self.pb_inputsetting.setText(_translate("Form", "SAVE SETTINGS"))
        self.label_2.setText(_translate("Form", "STATU::OFF"))
        self.tabConf.setTabText(self.tabConf.indexOf(self.tab_Configure), _translate("Form", "Configure "))
        self.tabConf.setTabText(self.tabConf.indexOf(self.tab_SerialSettings), _translate("Form", "Serial Settings"))
        self.tabDesign.setTabText(self.tabDesign.indexOf(self.Tab_Conf), _translate("Form", "Main Engine"))
        self.label_11.setText(_translate("Form", "Live Data"))
        self.label_12.setText(_translate("Form", "Deviation"))
        self.pushButton.setText(_translate("Form", "Test"))
        self.pushButton_2.setText(_translate("Form", "Save "))
        self.label_34.setText(_translate("Form", "SEA WATER PUMP"))
        self.label_38.setText(_translate("Form", "Live Data"))
        self.label_39.setText(_translate("Form", "Deviation"))
        self.pushButton_9.setText(_translate("Form", "Test"))
        self.pushButton_10.setText(_translate("Form", "Save "))
        self.label_41.setText(_translate("Form", "SEA WATER PUMP"))
        self.tabDesign.setTabText(self.tabDesign.indexOf(self.tab_2), _translate("Form", "Pumps"))
        self.tabDesign.setTabText(self.tabDesign.indexOf(self.tab), _translate("Form", "Cooling System"))
        self.tabDesign.setTabText(self.tabDesign.indexOf(self.tab_5), _translate("Form", "Lubricating System"))
        self.tabDesign.setTabText(self.tabDesign.indexOf(self.tab_6), _translate("Form", "Fuel System"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("Form", "New Item"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.tabDesign.setTabText(self.tabDesign.indexOf(self.tab_3), _translate("Form", "Monitoring Alerts"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
